version: "3.7"
services:
  api:
    container_name: api
    build:
      context: ./api/
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - GOOGLE_APPLICATION_CREDENTIALS=.firebase/service-account.json
      - API_KEY=AIzaSyBLXZ53TI5-g2Cy7JWi_WowSdqQ7ZAvin4
    ports:
      - 8080:8080

  web:
    container_name: round-up
    build:
      context: ./round-up/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
